org.gradle.jvmargs=-Xmx4G -XX:+HeapDumpOnOutOfMemoryError -Djava.net.preferIPv4Stack=true -Dhttps.protocols=TLSv1.2
systemProp.jdk.tls.client.protocols=TLSv1.2
android.useAndroidX=true
android.enableJetifier=true
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
android.nonFinalResIds=false
kotlin.incremental=false
kotlin.compiler.execution.strategy=in-process
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.workers.max=8